name: CI/CD Pipeline

on:
  push:
    branches: ["main", "CI/CD"]

jobs:
  test-frontend:
    name: Test & Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  deploy:
    name: Deploy to EC2
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/docker-banksajt
            git checkout CI/CD
            git pull origin CI/CD
            sudo docker compose up -d --build
